name: MLflow CI

on:
  push:
    branches:
      - main

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.10
          environment-file: conda.yaml
          activate-environment: iris_env
          auto-activate-base: false

      - name: Verify conda env
        shell: bash -l {0}
        run: |
          conda info --envs
          conda list

      - name: Run MLflow Project
        shell: bash -l {0}
        run: |
          conda activate iris_env
          mlflow run .

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-artifacts
          path: mlruns/
