name: MLflow CI

on:
  push:
    branches:
      - main

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: conda env update -f conda.yaml

      - name: Run MLflow project
        run: mlflow run .

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: mlflow-artifacts
          path: mlruns/
